version: '3.8'

services:
  redis:
    container_name: redis
    image: "redis:alpine"

    env_file:
      - .env

    command: redis-server --requirepass ${REDIS_PASSWORD}

    ports:
      - "6379:6379"

    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
